//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandCenter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandCenter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bountyPicture {
            get {
                object obj = ResourceManager.GetObject("bountyPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  no civilian casualties brought about by the holding party of the bounty contract.
        /// absolutley no civilian casualties brought about by any combatants in the contract&apos;s execution.
        /// the target returned alive and reasonably unharmed to the issuing party of the bounty contract.
        /// the target&apos;s identifiable remains returned to the issuing party of the bounty contract.
        ///out alerting local authorities (at the place of bounty&apos;s capture).
        /// absolutely no destruction of property by the holding party of the bounty co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string conditions {
            get {
                return ResourceManager.GetString("conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arson
        ///Computer Crime (Class 2)
        ///Conspiracy (Class 2)
        ///Counterfeiting
        ///Desertion
        ///Distribution of Illegal Weaponry
        ///Drug Trafficking / Distribution
        ///Embezzlement (First Degree)
        ///Enslavement
        ///Kidnapping
        ///Money Laundering
        ///Murder (First Degree)
        ///Piracy
        ///Racketeering
        ///Securities Fraud
        ///Trafficking of Sentient Species
        ///War Crimes.
        /// </summary>
        internal static string highRiskCrimes {
            get {
                return ResourceManager.GetString("highRiskCrimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jobsPicture {
            get {
                object obj = ResourceManager.GetObject("jobsPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aargau
        ///Aargonar
        ///Abhean
        ///Abregado-Rae
        ///Aduba
        ///Adumar
        ///Aeten
        ///Agamar
        ///Akrit&apos;tar
        ///Akuria
        ///Alderaan
        ///Aleen
        ///Allanteen
        ///Allon
        ///Almania
        ///Alpheridies
        ///Alsakan
        ///Alzoc
        ///Ambria
        ///Anaxes
        ///Andara
        ///Ando
        ///Ankus
        ///Anoth
        ///Ansion
        ///Antar
        ///Anteevy
        ///Anzat
        ///Aquaris
        ///Arami
        ///Arbra
        ///Argazda
        ///Aridus
        ///Arkania
        ///Askaj
        ///Ator
        ///Atraken
        ///Atravis
        ///Attahox
        ///Atzerri
        ///Axxila
        ///Azure
        ///Bacrana
        ///Bakura
        ///Balamak
        ///Balmorra
        ///Balnab
        ///Balosar
        ///Bandomeer
        ///Barab
        ///Baros
        ///Bastion
        ///Belasco
        ///Belderone
        ///Belkadan
        ///Bellassa
        ///Belnar
        ///Belsavis
        ///Berchest
        ///Berrol&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aiding and Abetting
        ///Assault
        ///Battery
        ///Burglarly
        ///Computer Crime (Class 5)
        ///Conspiracy (Class 5)
        ///Criminal Contempt of Court
        ///Disturbing the Peace
        ///Domestic Violence
        ///Drug Possession
        ///Embezzlement (Third Degree)
        ///Felony Escape (Second Degree)
        ///Fraud
        ///Illegal Citizenship
        ///Indecent Exposure
        ///Manslaughter (Involuntary)
        ///Possession of Illicit Materials
        ///Violation of Probation
        ///Public Intoxication
        ///Reckless Endangerment
        ///Shoplifting
        ///Solicitation
        ///Stalking
        ///Theft
        ///Vandalism
        ///Vehicle Operation Under the Influence.
        /// </summary>
        internal static string lowRiskCrimes {
            get {
                return ResourceManager.GetString("lowRiskCrimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adostic Arms
        ///Amberlandrax Armaments
        ///Antrech Arms
        ///Antrech Arms
        ///Arakyd Industries
        ///ArmaTek
        ///ArMek
        ///Atgar SpaceDefense
        ///Bacnor Armaments
        ///Baktoid Armor Workshop
        ///Baktoid Personal Ordnance
        ///Baril Tarn Collective
        ///Barimoq Industries
        ///BlasTech Industries
        ///Borstel Galactic Defense
        ///Bryn &amp; Gweith
        ///Caelli-Merced Syndicate
        ///Caliban
        ///Charendohl Exports, Ltd.
        ///CoMar Combat Systems
        ///Concordian Crescent Technologies
        ///Corellian Arms
        ///Corellian Personal Defense
        ///Corondexx
        ///Coronet Arms
        ///CoroTech
        ///Coruschal WeaponWorks        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manufacturers {
            get {
                return ResourceManager.GetString("manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory
        ///Aggravated Assault
        ///Blackmail
        ///Bribery
        ///Child Abandonment
        ///Child Abuse
        ///Computer Crime (Class 3)
        ///Conspiracy (Class 3)
        ///Credit Fraud
        ///Distribution of a Controlled Substance
        ///Embezzlement (Second Degree)
        ///Extortion
        ///Felony Escape (First Degree)
        ///Forgery
        ///Grand Larceny
        ///Identity Theft
        ///Insurance Fraud
        ///Manslaughter (Voluntary)
        ///Manufacturing of a Controlled Substance
        ///Murder (Second Degree)
        ///Perjury
        ///Possession of a Controlled Substance
        ///Prostitution
        ///Robbery
        ///Sexual Assault
        ///Smuggling
        ///Tax Evasion [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moderateRiskCrimes {
            get {
                return ResourceManager.GetString("moderateRiskCrimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abednedo
        ///Aleena
        ///Amani
        ///Angel
        ///Aqualish
        ///Asogian
        ///Balnab
        ///Besalisk
        ///Bith
        ///Caskadag
        ///Cerean
        ///Chalactan
        ///Chiss
        ///Clawdite
        ///Colicoid
        ///Dathomirian
        ///Devaronian
        ///Droid (Rogue)
        ///Duros
        ///Ewok
        ///Fisher
        ///Frigosian
        ///Gamorrean
        ///Geonosian
        ///Geren
        ///Gigoran
        ///Gossam
        ///Gran
        ///Grysk
        ///H&apos;nemthe
        ///Harch
        ///Holwuff
        ///Human
        ///Hutt
        ///Iktotchi
        ///Ishi Tib
        ///Ithorian
        ///Jawa
        ///Kage
        ///Kaleesh
        ///Kaminoan
        ///Kel Dor
        ///Klatooinian
        ///Lamproid
        ///Lannik
        ///Lasat
        ///Lurmen
        ///Mikkian
        ///Mirialan
        ///Mon Calamari
        ///Mustafarian
        ///Muun
        ///Nautolan
        ///Neimoidian
        ///Nu-Cosian
        ///Pau&apos;an
        ///Ph [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string races {
            get {
                return ResourceManager.GetString("races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap weaponPicture {
            get {
                object obj = ResourceManager.GetObject("weaponPicture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream wilhelm_scream {
            get {
                return ResourceManager.GetStream("wilhelm_scream", resourceCulture);
            }
        }
    }
}
